# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cc66ec32400b4679347668a1a31dfd1344e810ffa80bc1d54951e4d4506ba030849a4b9542bb10c784640aafcd492d272a036dcea9b07d35da3ff2f2996633d

test:
  secret_key_base: f6727f150cd55686515d7cbe80581493e7582560f976c14d9184e6e0de79d569a318ac345b3b5849f643d433c3fef1a58d61efb084d62e1414782989ac3f9c2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
